---

- name: Download dotNet install script
  ansible.builtin.get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: /tmp/dotnet_install.sh
    mode: '0755'

- name: "Install dotNet versions"
  ansible.builtin.shell: "./dotnet_install.sh --channel {{ item }}"
  args:
    chdir: /tmp
  loop: "{{ dotnet_versions }}"
