---

- name: Get Zoxide Install Script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
    dest: /tmp/zoxide_install.sh
    mode: '0755'
  register: zoxide_install_script

- name: Install Zoxide  with script
  become: true
  ansible.builtin.shell:
    cmd: /tmp/zoxide_install.sh
    executable: /bin/sh
  when: zoxide_install_script.changed
